In [6]:
import numpy as np

In [7]:
# excute ==> native code (c++) ==> faster 

In [8]:
nums = range(2,7)

In [22]:
arr = np.array(nums ,dtype=np.int64)

In [23]:
arr

array([2, 3, 4, 5, 6], dtype=int64)

In [24]:
type(arr)

numpy.ndarray

In [25]:
arr.dtype

dtype('int64')

In [26]:
arr.shape

(5,)

In [27]:
arr[0]

2

In [28]:
arr[-1]

6

In [32]:
arr[2:3]

array([4], dtype=int64)

In [33]:
arr[2::-1]

array([4, 3, 2], dtype=int64)

In [36]:
two=np.arange(4,20,3 , dtype=float)

In [37]:
two.size

6

In [38]:
# 2-D with iters

In [44]:
li = np.array([[12,13,14],[1,2,3],[10,20,30]])

In [45]:
li

array([[12, 13, 14],
       [ 1,  2,  3],
       [10, 20, 30]])

In [46]:
li = np.array2string(li)

In [47]:
li

'[[12 13 14]\n [ 1  2  3]\n [10 20 30]]'

In [48]:
li = np.array([[12,13,14],[1,2,3],[10,20,30,40]])

In [49]:
li

array([list([12, 13, 14]), list([1, 2, 3]), list([10, 20, 30, 40])],
      dtype=object)

In [50]:
type(li[0])

list

In [51]:
np.arange(100).reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [52]:
np.arange(100).reshape(10,5)

ValueError: cannot reshape array of size 100 into shape (10,5)

In [53]:
np.arange(100).reshape(-1,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [63]:
arr1 = np.arange(50)

In [64]:
arr2 = arr1.reshape(10,5)

In [65]:
arr1[0] = 1000

In [66]:
arr2

array([[1000,    1,    2,    3,    4],
       [   5,    6,    7,    8,    9],
       [  10,   11,   12,   13,   14],
       [  15,   16,   17,   18,   19],
       [  20,   21,   22,   23,   24],
       [  25,   26,   27,   28,   29],
       [  30,   31,   32,   33,   34],
       [  35,   36,   37,   38,   39],
       [  40,   41,   42,   43,   44],
       [  45,   46,   47,   48,   49]])

In [67]:
arr.shape

(5,)

In [68]:
arr1.shape

(50,)

In [69]:
arr2.shape

(10, 5)

In [70]:
sec = arr1.copy()

In [71]:
arr1[0]= 50

In [72]:
sec

array([1000,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
         22,   23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
         33,   34,   35,   36,   37,   38,   39,   40,   41,   42,   43,
         44,   45,   46,   47,   48,   49])

In [82]:
one = np.arange(10,30).reshape(4,5)

In [83]:
two = np.arange(70,50,-1).reshape(4,5)

In [84]:
one

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [85]:
two

array([[70, 69, 68, 67, 66],
       [65, 64, 63, 62, 61],
       [60, 59, 58, 57, 56],
       [55, 54, 53, 52, 51]])

In [86]:
one + two

array([[80, 80, 80, 80, 80],
       [80, 80, 80, 80, 80],
       [80, 80, 80, 80, 80],
       [80, 80, 80, 80, 80]])

In [87]:
one // two

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int32)

In [88]:
arr = np.arange(30).reshape(5,3,2)

In [90]:
arr[0].shape

(3, 2)

In [91]:
arr

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29]]])

In [95]:
arr = np.arange(120).reshape(5,4,3,2)

In [96]:
arr

array([[[[  0,   1],
         [  2,   3],
         [  4,   5]],

        [[  6,   7],
         [  8,   9],
         [ 10,  11]],

        [[ 12,  13],
         [ 14,  15],
         [ 16,  17]],

        [[ 18,  19],
         [ 20,  21],
         [ 22,  23]]],


       [[[ 24,  25],
         [ 26,  27],
         [ 28,  29]],

        [[ 30,  31],
         [ 32,  33],
         [ 34,  35]],

        [[ 36,  37],
         [ 38,  39],
         [ 40,  41]],

        [[ 42,  43],
         [ 44,  45],
         [ 46,  47]]],


       [[[ 48,  49],
         [ 50,  51],
         [ 52,  53]],

        [[ 54,  55],
         [ 56,  57],
         [ 58,  59]],

        [[ 60,  61],
         [ 62,  63],
         [ 64,  65]],

        [[ 66,  67],
         [ 68,  69],
         [ 70,  71]]],


       [[[ 72,  73],
         [ 74,  75],
         [ 76,  77]],

        [[ 78,  79],
         [ 80,  81],
         [ 82,  83]],

        [[ 84,  85],
         [ 86,  87],
         [ 88,  89]],

        [[ 90,  91]

In [97]:
arr[0].shape

(4, 3, 2)

In [105]:
arr = np.arange(60).reshape(5,2,3,2)

In [106]:
arr + np.arange(12).reshape(2,3,2)

array([[[[ 0,  2],
         [ 4,  6],
         [ 8, 10]],

        [[12, 14],
         [16, 18],
         [20, 22]]],


       [[[12, 14],
         [16, 18],
         [20, 22]],

        [[24, 26],
         [28, 30],
         [32, 34]]],


       [[[24, 26],
         [28, 30],
         [32, 34]],

        [[36, 38],
         [40, 42],
         [44, 46]]],


       [[[36, 38],
         [40, 42],
         [44, 46]],

        [[48, 50],
         [52, 54],
         [56, 58]]],


       [[[48, 50],
         [52, 54],
         [56, 58]],

        [[60, 62],
         [64, 66],
         [68, 70]]]])

In [107]:
arr + np.arange(6).reshape(2,3)

ValueError: operands could not be broadcast together with shapes (5,2,3,2) (2,3) 

In [108]:
arr + np.arange(6).reshape(3,2)

array([[[[ 0,  2],
         [ 4,  6],
         [ 8, 10]],

        [[ 6,  8],
         [10, 12],
         [14, 16]]],


       [[[12, 14],
         [16, 18],
         [20, 22]],

        [[18, 20],
         [22, 24],
         [26, 28]]],


       [[[24, 26],
         [28, 30],
         [32, 34]],

        [[30, 32],
         [34, 36],
         [38, 40]]],


       [[[36, 38],
         [40, 42],
         [44, 46]],

        [[42, 44],
         [46, 48],
         [50, 52]]],


       [[[48, 50],
         [52, 54],
         [56, 58]],

        [[54, 56],
         [58, 60],
         [62, 64]]]])

In [109]:
arr

array([[[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]]],


       [[[12, 13],
         [14, 15],
         [16, 17]],

        [[18, 19],
         [20, 21],
         [22, 23]]],


       [[[24, 25],
         [26, 27],
         [28, 29]],

        [[30, 31],
         [32, 33],
         [34, 35]]],


       [[[36, 37],
         [38, 39],
         [40, 41]],

        [[42, 43],
         [44, 45],
         [46, 47]]],


       [[[48, 49],
         [50, 51],
         [52, 53]],

        [[54, 55],
         [56, 57],
         [58, 59]]]])

In [110]:
arr2 = np.arange(6).reshape(3,2)

In [112]:
arr2

array([[0, 1],
       [2, 3],
       [4, 5]])

In [114]:
np.zeros([3,4,6], dtype = int)

array([[[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]]])

In [116]:
np.zeros(range(2,4), dtype = int)

array([[0, 0, 0],
       [0, 0, 0]])

In [117]:
np.ones([3,4,6], dtype = int)

array([[[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]]])

In [118]:
np.full((3,4),5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [119]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [120]:
np.eye(5,dtype =int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [121]:
one.T

array([[10, 15, 20, 25],
       [11, 16, 21, 26],
       [12, 17, 22, 27],
       [13, 18, 23, 28],
       [14, 19, 24, 29]])

In [122]:
arr = np.arange(20).reshape(5,4)

In [123]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [124]:
arr.sum

<function ndarray.sum>

In [125]:
arr.sum()

190

In [126]:
arr.sum(axis=0)

array([40, 45, 50, 55])

In [127]:
arr.sum(axis=1)

array([ 6, 22, 38, 54, 70])

In [128]:
arr.mean()

9.5

In [129]:
arr.mean(axis=0)

array([ 8.,  9., 10., 11.])

In [130]:
arr.std()

5.766281297335398

In [131]:
arr.prod()

0

In [132]:
arr.prod(axis=1)

array([    0,   840,  7920, 32760, 93024])

In [154]:
arr.sum(axis=1, keepdims=True)

array([[ 6],
       [22],
       [38],
       [54],
       [70]])

In [134]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [135]:
np.sin(np.pi)

1.2246467991473532e-16

In [136]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [137]:
np.linspace(1,np.pi,10)

array([1.        , 1.23795474, 1.47590948, 1.71386422, 1.95181896,
       2.1897737 , 2.42772844, 2.66568318, 2.90363791, 3.14159265])

In [138]:
a =np.linspace(1,np.pi,10)

In [139]:
np.sin(a)

array([8.41470985e-01, 9.45117729e-01, 9.95501620e-01, 9.89783234e-01,
       9.28284836e-01, 8.14472215e-01, 6.54759373e-01, 4.58147051e-01,
       2.35715491e-01, 1.22464680e-16])

In [140]:
np.exp(a)

array([ 2.71828183,  3.44855306,  4.37501294,  5.55036792,  7.0414841 ,
        8.93319127, 11.33310893, 14.37776872, 18.24038176, 23.14069263])

In [141]:
b = np.linspace(1,10,10)

In [142]:
np.exp2(b)

array([   2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,  512.,
       1024.])